name: first-workflow
on:
  workflow_dispatch:
    inputs:
      un:
        description: 'wqerty'
        required: true
        type: string

jobs:
  say-my-name:
    runs-on: ubuntu-latest
    steps:
      - name: sayq
        uses: ./github/actions/testaction
        with:
          username: ${{ inputs.un }}