name: first-workflow
on:
  workflow_dispatch:
    inputs:
      un:
        description: 'wqerty'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: qwerty
      cancel-in-progress: true
    steps:
      - name: test
        run: echo hello