name: first-workflow
on:
  workflow_dispatch:
    inputs:
      listqwer:
        description: 'list513'
        required: true
        type: choice
        options:
          - empty513
          - qwert
          - wasd
jobs:
  hello:
    env:
      EMPTY513: boss
    runs-on: ubuntu-latest
    steps:
      - name: say-dispatch
        run: echo ${{ github.event.inputs.listqwer }}
      - name: say-whoami
        run: echo ${{ env.EMPTY513 }}
      - name: say-workspace
        run: echo ${{ github.workspace }}
      - name: say-workspace
        run: echo ${{ github.actor }}
      - name: say-gh
        run: echo ${{ vars.GHENV }}
