name: first-workflow
on:
  workflow_dispatch:
    inputs:
      listqwer:
        description: 'list513'
        required: true
        type: choice
        options:
          - empty513
          - qwert
          - wasd
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo hello ubun
