name: first-workflow
on:
  workflow_dispatch:
    inputs:
      un:
        description: 'wqerty'
        required: true
        type: string

jobs:
  say-my-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sayq
        uses: ./.github/actions/testaction
        with:
          username: ${{ inputs.un }}
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        me: [empty513, ivan, johan]
        whoami: [boss, pro, superman]
        exclude:
          - me: ivan
            whoami: superman
        include:
          - me: khotko
            whoami: ultraman
    steps:
      - name: iam
        run: echo '${{ matrix.me }} is ${{ matrix.whoami }}'