name: first-workflow
on:
  workflow_dispatch:
    inputs:
      listqwer:
        description: 'list513'
        required: true
        type: choice
        options:
          - empty513
          - qwert
          - wasd
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: mistake
        run: ecco 
      - name: if-succes
        if: success()
        run: echo succes >> art.txt
      - name: if-fail
        if: failure()
        run: echo failure >> art.txt
      - name: save-artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: art.txt

